version: "2.1"
services:

  mysql:
    image: ${RS_PREFIX}/mysql:5.7.25
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${RS_MYSQL_PASSWORD}
    volumes:
      - ${RS_BASE}/riskscanner/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${RS_BASE}/riskscanner/bin/mysql:/docker-entrypoint-initdb.d/
      - riskscanner-mysql-data:/var/lib/mysql
    networks:
      - riskscanner-network

volumes:
  riskscanner-mysql-data:
    driver_opts:
      type: none
      device: ${RS_BASE}/riskscanner/data/mysql
      o: bind